### ISSUE TITLE
Removing the mapping types from the elasticsearch store 

### ISSUE THREAD

**Issue by iloshinik** [siddhi-io/siddhi-store-elasticsearch#19]
**Description:**
As sending type is deprecated in from ELK version 7.0 and will not be supported from version 8.0 onwards [1], when publishing events to elasticsearch, the following WARN message can be observed in the Analytics node for each event.

`WARN {org.elasticsearch.client.RestClient} - request [POST http://localhost:9200/_bulk?timeout=1m] returned 1 warnings: [299 Elasticsearch-7.0.0-b7e28a7 "[types removal] Specifying types in bulk requests is deprecated."]`

**Affected Product Version:**
v1.1.3

**Steps to reproduce:**
1. Set up Elastic search.
2. Enable analytics on API-M 2.6.0.
3. Replace the existing **<API-M_ANALYTICS_HOME>/lib/siddhi-store-elasticsearch-v1.0.5.jar** with the latest **siddhi-store-elasticsearch-v1.1.3.jar** in [2].
4. Configure the credentials and deploy the siddhi app **APIM_ELASTICSEARCH.siddhi app** in <API-M_ANALYTICS_HOME>/wso2/worker/deployment/siddhi-files directory in-order to publish events to elasticsearh.
5. Start the API-M and API-M Analytics servers and publish events to elasticsearch by invoking APIs.
6. The above WARN message can be observed for each event.

[1]. https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html#_schedule_for_removal_of_mapping_types

[2]. https://store.wso2.com/store/assets/analyticsextension/list?q=%22_default%22%3A%22elastic%22

**Comment by ramindu90** [comment]
fixed in https://github.com/siddhi-io/siddhi-store-elasticsearch/pull/25
