### ISSUE TITLE
Write data in the root field "_source" of document in elasticsearch

### ISSUE THREAD

**Issue by tr0mb1r** [siddhi-io/siddhi-store-elasticsearch#31]
**Description:**
Elasticsearch module 3.0.0 doesn't write data to the root of document (in field _source).

**Suggested Labels:**
siddhi,elasticsearch

**Suggested Assignees:**
@suhothayan 

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
```
@source(type = 'http', receiver.url = "http://0.0.0.0:8006/nlins",@map(type = 'json',@attributes(json='$.event')))
define stream NlinsStream (json string);

@store(type='elasticsearch',hostname='localhost',port='9200',index.name='siddhi')
define table Elastic (event1 string);

partition with (json:getString(json,"computer_name") of NlinsStream)
begin
    from every e1=NlinsStream[RULE#1], e2=NlinsStream[RULE#2], e3=NlinsStream[RULE3]
    select json:toString(json:setElement(e1.json,'$',"updated",'new_field')) as event1
    insert into Elastic;
end;
```
The result is:
```
{
        "_index" : "siddhi",
        "_type" : "_doc",
        "_id" : "KRwl3mwBgY4BQ9S8DCa9",
        "_score" : 1.0,
        "_source" : {
          "event1" : """{MY_JSON_DATA}""",
        }
}
```
Expected:
```
{
        "_index" : "siddhi",
        "_type" : "_doc",
        "_id" : "KRwl3mwBgY4BQ9S8DCa9",
        "_score" : 1.0,
        "_source" : {
          {MY_JSON_DATA},
        }
}
```

**Comment by suhothayan** [comment]
I believe we can support this by adding a property to the `@store(type='elasticsearch')` annotation to omit column names. 
By doing this if the table has a single attribute then the events will be written to elasticsearch as 
```
{
        "_index" : "siddhi",
        "_type" : "_doc",
        "_id" : "KRwl3mwBgY4BQ9S8DCa9",
        "_score" : 1.0,
        "_source" : {
          DATA1
        }
}
```   
and if it has more than one attribute then it stores them in as a JSON array in the order they have been defined in the table. 
```
{
        "_index" : "siddhi",
        "_type" : "_doc",
        "_id" : "KRwl3mwBgY4BQ9S8DCa9",
        "_score" : 1.0,
        "_source" : {
          [DATA1, DATA2, DATA3]
        }
}
```   
WDYT?

**Comment by tr0mb1r** [comment]
I'm agree with first condition, but with second I think it would be better to store each DATA in separate document. Also i'm not sure that you can store array in _source of document.

**Comment by suhothayan** [comment]
@tr0mb1r can elaborate on your use case here. 
After writing the JSON, are you planning to use Siddhi t read the messages back? Or some other system is going to perform the read operation?

**Comment by tr0mb1r** [comment]
> After writing the JSON, are you planning to use Siddhi t read the messages back? 

Not for my case, but I think it would be usefull feature to use elastic as source in siddhi

> Or some other system is going to perform the read operation?

I'm using elastic as the last storage system with comfort search mechanism for other systems

**Comment by suhothayan** [comment]
We need to create a sink to achieve this. 
We will work on this
